export interface Language {
  code: string;
  englishName: string;
  nativeName: string;
}

export const LANGUAGES: Language[] = [
  { code: "ab", englishName: "Abkhazian", nativeName: "Аҧсуа" },
  { code: "aa", englishName: "Afar", nativeName: "Afaraf" },
  { code: "af", englishName: "Afrikaans", nativeName: "Afrikaans" },
  { code: "ak", englishName: "Akan", nativeName: "Akan" },
  { code: "sq", englishName: "Albanian", nativeName: "Shqip" },
  { code: "am", englishName: "Amharic", nativeName: "አማርኛ" },
  { code: "ar", englishName: "Arabic", nativeName: "العربية" },
  { code: "an", englishName: "Aragonese", nativeName: "Aragonés" },
  { code: "hy", englishName: "Armenian", nativeName: "Հայերեն" },
  { code: "as", englishName: "Assamese", nativeName: "অসমীয়া" },
  { code: "av", englishName: "Avaric", nativeName: "Авар" },
  { code: "ae", englishName: "Avestan", nativeName: "Avesta" },
  { code: "ay", englishName: "Aymara", nativeName: "Aymar" },
  { code: "az", englishName: "Azerbaijani", nativeName: "Azərbaycan" },
  { code: "bm", englishName: "Bambara", nativeName: "Bamanankan" },
  { code: "ba", englishName: "Bashkir", nativeName: "Башҡорт" },
  { code: "eu", englishName: "Basque", nativeName: "Euskara" },
  { code: "be", englishName: "Belarusian", nativeName: "Беларуская" },
  { code: "bn", englishName: "Bengali", nativeName: "বাংলা" },
  { code: "bh", englishName: "Bihari", nativeName: "भोजपुरी" },
  { code: "bi", englishName: "Bislama", nativeName: "Bislama" },
  { code: "bs", englishName: "Bosnian", nativeName: "Bosanski" },
  { code: "br", englishName: "Breton", nativeName: "Brezhoneg" },
  { code: "bg", englishName: "Bulgarian", nativeName: "Български" },
  { code: "my", englishName: "Burmese", nativeName: "မြန်မာဘာသာ" },
  { code: "ca", englishName: "Catalan", nativeName: "Català" },
  { code: "ch", englishName: "Chamorro", nativeName: "Chamoru" },
  { code: "ce", englishName: "Chechen", nativeName: "Нохчийн" },
  { code: "ny", englishName: "Chichewa", nativeName: "ChiCheŵa" },
  { code: "zh", englishName: "Chinese (Simplified)", nativeName: "中文（简体）" },
  { code: "zh-TW", englishName: "Chinese (Traditional)", nativeName: "中文（繁體）" },
  { code: "cv", englishName: "Chuvash", nativeName: "Чӑваш" },
  { code: "kw", englishName: "Cornish", nativeName: "Kernewek" },
  { code: "co", englishName: "Corsican", nativeName: "Corsu" },
  { code: "cr", englishName: "Cree", nativeName: "ᓀᐦᐃᔭᐍᐏᐣ" },
  { code: "hr", englishName: "Croatian", nativeName: "Hrvatski" },
  { code: "cs", englishName: "Czech", nativeName: "Čeština" },
  { code: "da", englishName: "Danish", nativeName: "Dansk" },
  { code: "dv", englishName: "Divehi", nativeName: "ދިވެހި" },
  { code: "nl", englishName: "Dutch", nativeName: "Nederlands" },
  { code: "dz", englishName: "Dzongkha", nativeName: "རྫོང་ཁ" },
  { code: "en", englishName: "English", nativeName: "English" },
  { code: "eo", englishName: "Esperanto", nativeName: "Esperanto" },
  { code: "et", englishName: "Estonian", nativeName: "Eesti" },
  { code: "ee", englishName: "Ewe", nativeName: "Eʋegbe" },
  { code: "fo", englishName: "Faroese", nativeName: "Føroyskt" },
  { code: "fj", englishName: "Fijian", nativeName: "Vosa Vakaviti" },
  { code: "fi", englishName: "Finnish", nativeName: "Suomi" },
  { code: "fr", englishName: "French", nativeName: "Français" },
  { code: "ff", englishName: "Fula", nativeName: "Fulfulde" },
  { code: "gl", englishName: "Galician", nativeName: "Galego" },
  { code: "ka", englishName: "Georgian", nativeName: "ქართული" },
  { code: "de", englishName: "German", nativeName: "Deutsch" },
  { code: "el", englishName: "Greek", nativeName: "Ελληνικά" },
  { code: "gn", englishName: "Guaraní", nativeName: "Avañe'ẽ" },
  { code: "gu", englishName: "Gujarati", nativeName: "ગુજરાતી" },
  { code: "ht", englishName: "Haitian Creole", nativeName: "Kreyòl Ayisyen" },
  { code: "ha", englishName: "Hausa", nativeName: "Hausa" },
  { code: "he", englishName: "Hebrew", nativeName: "עברית" },
  { code: "hz", englishName: "Herero", nativeName: "Otjiherero" },
  { code: "hi", englishName: "Hindi", nativeName: "हिन्दी" },
  { code: "ho", englishName: "Hiri Motu", nativeName: "Hiri Motu" },
  { code: "hu", englishName: "Hungarian", nativeName: "Magyar" },
  { code: "ia", englishName: "Interlingua", nativeName: "Interlingua" },
  { code: "id", englishName: "Indonesian", nativeName: "Bahasa Indonesia" },
  { code: "ie", englishName: "Interlingue", nativeName: "Interlingue" },
  { code: "ga", englishName: "Irish", nativeName: "Gaeilge" },
  { code: "ig", englishName: "Igbo", nativeName: "Igbo" },
  { code: "ik", englishName: "Inupiaq", nativeName: "Iñupiaq" },
  { code: "io", englishName: "Ido", nativeName: "Ido" },
  { code: "is", englishName: "Icelandic", nativeName: "Íslenska" },
  { code: "it", englishName: "Italian", nativeName: "Italiano" },
  { code: "iu", englishName: "Inuktitut", nativeName: "ᐃᓄᒃᑎᑐᑦ" },
  { code: "ja", englishName: "Japanese", nativeName: "日本語" },
  { code: "jv", englishName: "Javanese", nativeName: "ꦧꦱꦗꦮ" },
  { code: "kl", englishName: "Kalaallisut", nativeName: "Kalaallisut" },
  { code: "kn", englishName: "Kannada", nativeName: "ಕನ್ನಡ" },
  { code: "kr", englishName: "Kanuri", nativeName: "Kanuri" },
  { code: "ks", englishName: "Kashmiri", nativeName: "كشميري" },
  { code: "kk", englishName: "Kazakh", nativeName: "Қазақ" },
  { code: "km", englishName: "Khmer", nativeName: "ភាសាខ្មែរ" },
  { code: "ki", englishName: "Kikuyu", nativeName: "Gĩkũyũ" },
  { code: "rw", englishName: "Kinyarwanda", nativeName: "Ikinyarwanda" },
  { code: "ky", englishName: "Kyrgyz", nativeName: "Кыргызча" },
  { code: "kv", englishName: "Komi", nativeName: "Коми" },
  { code: "kg", englishName: "Kongo", nativeName: "KiKongo" },
  { code: "ko", englishName: "Korean", nativeName: "한국어" },
  { code: "ku", englishName: "Kurdish", nativeName: "Kurdî" },
  { code: "kj", englishName: "Kwanyama", nativeName: "Kuanyama" },
  { code: "la", englishName: "Latin", nativeName: "Latina" },
  { code: "lb", englishName: "Luxembourgish", nativeName: "Lëtzebuergesch" },
  { code: "lg", englishName: "Luganda", nativeName: "Luganda" },
  { code: "li", englishName: "Limburgish", nativeName: "Limburgs" },
  { code: "ln", englishName: "Lingala", nativeName: "Lingála" },
  { code: "lo", englishName: "Lao", nativeName: "ລາວ" },
  { code: "lt", englishName: "Lithuanian", nativeName: "Lietuvių" },
  { code: "lu", englishName: "Luba-Katanga", nativeName: "Kiluba" },
  { code: "lv", englishName: "Latvian", nativeName: "Latviešu" },
  { code: "gv", englishName: "Manx", nativeName: "Gaelg" },
  { code: "mk", englishName: "Macedonian", nativeName: "Македонски" },
  { code: "mg", englishName: "Malagasy", nativeName: "Malagasy" },
  { code: "ms", englishName: "Malay", nativeName: "Bahasa Melayu" },
  { code: "ml", englishName: "Malayalam", nativeName: "മലയാളം" },
  { code: "mt", englishName: "Maltese", nativeName: "Malti" },
  { code: "mi", englishName: "Māori", nativeName: "Te Reo Māori" },
  { code: "mr", englishName: "Marathi", nativeName: "मराठी" },
  { code: "mh", englishName: "Marshallese", nativeName: "Kajin M̧ajeļ" },
  { code: "mn", englishName: "Mongolian", nativeName: "Монгол" },
  { code: "na", englishName: "Nauru", nativeName: "Dorerin Naoero" },
  { code: "nv", englishName: "Navajo", nativeName: "Diné bizaad" },
  { code: "nd", englishName: "North Ndebele", nativeName: "isiNdebele" },
  { code: "ne", englishName: "Nepali", nativeName: "नेपाली" },
  { code: "ng", englishName: "Ndonga", nativeName: "Owambo" },
  { code: "nb", englishName: "Norwegian Bokmål", nativeName: "Norsk Bokmål" },
  { code: "nn", englishName: "Norwegian Nynorsk", nativeName: "Norsk Nynorsk" },
  { code: "no", englishName: "Norwegian", nativeName: "Norsk" },
  { code: "ii", englishName: "Nuosu", nativeName: "ꆈꌠ꒿" },
  { code: "nr", englishName: "South Ndebele", nativeName: "isiNdebele" },
  { code: "oc", englishName: "Occitan", nativeName: "Occitan" },
  { code: "oj", englishName: "Ojibwe", nativeName: "ᐊᓂᔑᓈᐯᒧᐎᓐ" },
  { code: "cu", englishName: "Old Church Slavonic", nativeName: "Словѣньскъ" },
  { code: "om", englishName: "Oromo", nativeName: "Afaan Oromoo" },
  { code: "or", englishName: "Oriya", nativeName: "ଓଡ଼ିଆ" },
  { code: "os", englishName: "Ossetian", nativeName: "Ирон" },
  { code: "pa", englishName: "Punjabi", nativeName: "ਪੰਜਾਬੀ" },
  { code: "pi", englishName: "Pāli", nativeName: "पाऴि" },
  { code: "fa", englishName: "Persian", nativeName: "فارسی" },
  { code: "pl", englishName: "Polish", nativeName: "Polski" },
  { code: "ps", englishName: "Pashto", nativeName: "پښتو" },
  { code: "pt", englishName: "Portuguese", nativeName: "Português" },
  { code: "pt-BR", englishName: "Portuguese (Brazil)", nativeName: "Português (Brasil)" },
  { code: "qu", englishName: "Quechua", nativeName: "Runa Simi" },
  { code: "rm", englishName: "Romansh", nativeName: "Rumantsch" },
  { code: "rn", englishName: "Kirundi", nativeName: "Ikirundi" },
  { code: "ro", englishName: "Romanian", nativeName: "Română" },
  { code: "ru", englishName: "Russian", nativeName: "Русский" },
  { code: "sa", englishName: "Sanskrit", nativeName: "संस्कृतम्" },
  { code: "sc", englishName: "Sardinian", nativeName: "Sardu" },
  { code: "sd", englishName: "Sindhi", nativeName: "سنڌي" },
  { code: "se", englishName: "Northern Sami", nativeName: "Davvisámegiella" },
  { code: "sm", englishName: "Samoan", nativeName: "Gagana Samoa" },
  { code: "sg", englishName: "Sango", nativeName: "Yângâ tî sängö" },
  { code: "sr", englishName: "Serbian", nativeName: "Српски" },
  { code: "gd", englishName: "Scottish Gaelic", nativeName: "Gàidhlig" },
  { code: "sn", englishName: "Shona", nativeName: "ChiShona" },
  { code: "si", englishName: "Sinhala", nativeName: "සිංහල" },
  { code: "sk", englishName: "Slovak", nativeName: "Slovenčina" },
  { code: "sl", englishName: "Slovenian", nativeName: "Slovenščina" },
  { code: "so", englishName: "Somali", nativeName: "Soomaaliga" },
  { code: "st", englishName: "Southern Sotho", nativeName: "Sesotho" },
  { code: "es", englishName: "Spanish", nativeName: "Español" },
  { code: "su", englishName: "Sundanese", nativeName: "Basa Sunda" },
  { code: "sw", englishName: "Swahili", nativeName: "Kiswahili" },
  { code: "ss", englishName: "Swati", nativeName: "SiSwati" },
  { code: "sv", englishName: "Swedish", nativeName: "Svenska" },
  { code: "ta", englishName: "Tamil", nativeName: "தமிழ்" },
  { code: "te", englishName: "Telugu", nativeName: "తెలుగు" },
  { code: "tg", englishName: "Tajik", nativeName: "Тоҷикӣ" },
  { code: "th", englishName: "Thai", nativeName: "ภาษาไทย" },
  { code: "ti", englishName: "Tigrinya", nativeName: "ትግርኛ" },
  { code: "bo", englishName: "Tibetan", nativeName: "བོད་ཡིག" },
  { code: "tk", englishName: "Turkmen", nativeName: "Türkmen" },
  { code: "tl", englishName: "Tagalog", nativeName: "Tagalog" },
  { code: "tn", englishName: "Tswana", nativeName: "Setswana" },
  { code: "to", englishName: "Tonga", nativeName: "Faka Tonga" },
  { code: "tr", englishName: "Turkish", nativeName: "Türkçe" },
  { code: "ts", englishName: "Tsonga", nativeName: "Xitsonga" },
  { code: "tt", englishName: "Tatar", nativeName: "Татар" },
  { code: "tw", englishName: "Twi", nativeName: "Twi" },
  { code: "ty", englishName: "Tahitian", nativeName: "Reo Tahiti" },
  { code: "ug", englishName: "Uyghur", nativeName: "ئۇيغۇرچە" },
  { code: "uk", englishName: "Ukrainian", nativeName: "Українська" },
  { code: "ur", englishName: "Urdu", nativeName: "اردو" },
  { code: "uz", englishName: "Uzbek", nativeName: "O'zbek" },
  { code: "ve", englishName: "Venda", nativeName: "Tshivenḓa" },
  { code: "vi", englishName: "Vietnamese", nativeName: "Tiếng Việt" },
  { code: "vo", englishName: "Volapük", nativeName: "Volapük" },
  { code: "wa", englishName: "Walloon", nativeName: "Walon" },
  { code: "cy", englishName: "Welsh", nativeName: "Cymraeg" },
  { code: "wo", englishName: "Wolof", nativeName: "Wollof" },
  { code: "fy", englishName: "Western Frisian", nativeName: "Frysk" },
  { code: "xh", englishName: "Xhosa", nativeName: "isiXhosa" },
  { code: "yi", englishName: "Yiddish", nativeName: "ייִדיש" },
  { code: "yo", englishName: "Yoruba", nativeName: "Yorùbá" },
  { code: "za", englishName: "Zhuang", nativeName: "Saɯ cueŋƅ" },
  { code: "zu", englishName: "Zulu", nativeName: "isiZulu" },
];

export function getLanguageByCode(code: string): Language {
  return LANGUAGES.find((l) => l.code === code) ?? { code, englishName: code, nativeName: code };
}
